# Aug 11

In [3]:
# Create the range using :arenge()
import numpy as np

arr_range =np.arange(2,15,2)
arr_range

array([ 2,  4,  6,  8, 10, 12, 14])

In [4]:
#create the linespaced
lin_space =np.linspace(0,1,10)   # we can displya how much we want using (3,10)
lin_space

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [5]:
# create the random array
array = np.random.rand(3,4)
array

array([[0.38344875, 0.46158924, 0.96189647, 0.61554951],
       [0.43026381, 0.34972865, 0.43016229, 0.90632384],
       [0.53437468, 0.21711904, 0.62602327, 0.02743701]])

In [6]:
# create the random integer array
array = np.random.randint(1,10,(4,4))
array

array([[2, 6, 7, 3],
       [9, 9, 8, 2],
       [7, 1, 8, 9],
       [4, 7, 8, 3]], dtype=int32)

In [7]:
array = np.random.randint(1,10,(4,4))
array.ndim

2

In [8]:
array = np.random.randint(1,10,(4,4))
array.shape

(4, 4)

In [9]:
age = np.random.randint(20,30,100)
np.sort(age)

array([20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21,
       21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 23, 23,
       23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 24, 24, 24,
       25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 26, 26, 26, 26, 26, 26,
       26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27,
       27, 27, 28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, 29],
      dtype=int32)

In [10]:
# convert the list into nympy arry

list1 = [1,2,3,4,5,6]
array =np.array(list1)                   # either we can put list in arry

list1


[1, 2, 3, 4, 5, 6]

In [11]:
array =np.array([[1,2,3,4],
                [2,3,4,5]])
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [12]:
# method 1: shape
array.shape    # (rowX column)

(2, 4)

In [13]:
# check the diamenstion of array
# method:2 ndim

array.ndim

2

In [14]:
# chaec the dtype of value
# method3:

array.dtype

dtype('int64')

In [15]:
# check the itemsize

array.itemsize

8

In [16]:
# check the memory of array
array.nbytes

64

In [17]:
# transpose the array
# row become cloumn and column become array

array.T
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [18]:
array.T


array([[1, 2],
       [2, 3],
       [3, 4],
       [4, 5]])

In [19]:
# real num and imaginery number called as complex num
#create the complex num
a = np.array([1+2j,3+4j])
a.real               # used to acces real num
                


array([1., 3.])

In [20]:
a.imag     #used to acess imaginary num

array([2., 4.])

In [21]:
# flat array

array.flat

In [22]:
array.min

<function ndarray.min>

In [23]:
array.max

<function ndarray.max>

In [24]:
array.sum()

np.int64(24)

In [25]:
array

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [26]:
array.sum(axis=0)

array([3, 5, 7, 9])

In [27]:
array.sum(axis=1)

array([10, 14])

In [28]:
# reshap()
# change the shape in array
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [29]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
# count the nonzero()
name =['Male','Female']
Gender =np.random.choice(name,10)
Gender

array(['Male', 'Female', 'Male', 'Male', 'Female', 'Male', 'Female',
       'Male', 'Male', 'Male'], dtype='<U6')

In [31]:
# genarete the float value

Salary =np.random.uniform(10000,25000,10)
Salary

array([15377.87411107, 24046.69581148, 23606.06419329, 20405.83769259,
       17263.20205166, 11436.32800568, 11666.76679778, 15257.18462873,
       19950.29365854, 11888.73482887])

In [32]:
Salary =np.random.uniform(10000,25000,10)
np.round(Salary,2)

array([13482.29, 21623.83, 12828.73, 10015.41, 12498.81, 21421.31,
       21752.47, 20326.59, 12732.59, 16402.6 ])

In [33]:
Age =np.random.randint(20,30,100)
Age

array([27, 23, 24, 28, 23, 21, 26, 22, 25, 24, 22, 21, 24, 23, 22, 29, 25,
       21, 20, 25, 26, 20, 24, 29, 21, 25, 23, 27, 24, 26, 29, 25, 23, 29,
       27, 27, 23, 29, 28, 26, 24, 25, 27, 29, 28, 28, 24, 22, 29, 22, 27,
       24, 26, 25, 22, 23, 29, 29, 28, 22, 26, 26, 25, 26, 27, 25, 29, 26,
       21, 22, 21, 28, 25, 20, 24, 25, 28, 27, 23, 20, 20, 28, 25, 27, 24,
       25, 23, 29, 24, 27, 28, 21, 24, 25, 27, 29, 21, 24, 21, 20],
      dtype=int32)

In [34]:
#id column start from 100
# name column 
#Gender 
# dept 
#exp
#role
#salary

# size 500*7


In [35]:
# ID
ID =np.arange(100,201)
ID
# name:
Name =["sandy","sandeep","santosh","savi","vaibhav","pooja"]
Name =np.random.choice(name,100)
# gender
Gender =['male','Female']
Gender = np.random.choice(g,100)
#dep 
dept =["It","hr","finance","call center"]
dept = np.random.choice(dept,100)
#exp
exp = np.random.uniform(0,20,100)
exp =np.round(exp,1)
# role
role =["data scientest","developer","tester","AI engineer","devops"]
role =np.random.choice(role,100)
#salary
Salary =np.random.uniform(45000,100000,100)
salary= np.round(Salary,2)

In [3]:
import pandas as pd

DataFrame = df

NameError: name 'df' is not defined

In [8]:


df = pd.DataFrame({
    "ID": ID,
    "Name":Name,
    "Gender":Gender,
    "Department":dept,
    "EXP":exp,
    "JOB role":role,
    "Salary":Salary
})

    

NameError: name 'ID' is not defined

In [9]:
df.head()

NameError: name 'df' is not defined

In [ ]:
# 